# Urls
BASE = "https://linkedin.com/"
JOBS = BASE + "jobs/"
SEARCH = JOBS + "search/?"

# Job Filter
# Date posted
PAST_WEEK = 'TPR=r604800'
PAST_24_HOURS = 'TPR=r86400'
PAST_MONTH = 'TPR=r2592000'

# Minimum salary
SALARY_40K = 'SB2=1'
SALARY_60K = 'SB2=2'
SALARY_80K = 'SB2=3'
SALARY_100K = 'SB2=4'
SALARY_120K = 'SB2=5'
SALARY_140K = 'SB2=6'
SALARY_160K = 'SB2=7'
SALARY_180K = 'SB2=8'
SALARY_200K = 'SB2=9'

# Onsite/Remote
ONSITE = 'WT=1'
REMOTE = 'WT=2'
HYBRID = 'WT=3'

# Job Type
FULL_TIME = 'JT=F'
PART_TIME = 'JT=P'
CONTRACT = 'JT=C'
TEMPORARY = 'JT=T'
VOLUNTEER = 'JT=V'
INTERNSHIP_JOB = 'JT=I'
OTHER = 'JT=O'

# Experience Level
INTERNSHIP_EXP = 'E=1'
ENTRY_LEVEL = 'E=2'
ASSOCIATE = 'E=3'
MID_SENIOR_LEVEL = 'E=4'
DIRECTOR = 'E=5'
EXECUTIVE = 'E=6'

JOB_NUMBER_START = '&start='