# Generated by Django 4.1.6 on 2023-02-08 22:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('company_name', models.CharField(max_length=50)),
                ('company_logo_url', models.CharField(max_length=100)),
                ('job_type', models.CharField(max_length=20)),
                ('remote_status', models.CharField(max_length=8)),
                ('salary_start', models.IntegerField()),
                ('salary_end', models.IntegerField()),
                ('date_listed', models.DateField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
